#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : Pint
Version  : 0.6
Release  : 10
URL      : https://pypi.python.org/packages/source/P/Pint/Pint-0.6.zip
Source0  : https://pypi.python.org/packages/source/P/Pint/Pint-0.6.zip
Summary  : Physical quantities module
Group    : Development/Tools
License  : BSD-3-Clause
Requires: Pint-python
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
Pint: a Python units library
============================
Pint is Python module/package to define, operate and manipulate physical
quantities: the product of a numerical value and a unit of measurement.
It allows arithmetic operations between them and conversions from and
to different units.

%package python
Summary: python components for the Pint package.
Group: Default

%description python
python components for the Pint package.


%prep
%setup -q -n Pint-0.6

%build
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
python2 setup.py test
%install
rm -rf %{buildroot}
python2 setup.py build -b py2 install --root=%{buildroot}
python3 setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
