#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : Pint
Version  : 0.8.1
Release  : 26
URL      : http://pypi.debian.net/Pint/Pint-0.8.1.tar.gz
Source0  : http://pypi.debian.net/Pint/Pint-0.8.1.tar.gz
Summary  : Physical quantities module
Group    : Development/Tools
License  : BSD-3-Clause
Requires: Pint-python3
Requires: Pint-license
Requires: Pint-python
BuildRequires : buildreq-distutils3
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python3-dev
BuildRequires : setuptools

%description
======================
        
        Pint is a Python package to define, operate and manipulate physical

%package license
Summary: license components for the Pint package.
Group: Default

%description license
license components for the Pint package.


%package python
Summary: python components for the Pint package.
Group: Default
Requires: Pint-python3
Provides: pint-python

%description python
python components for the Pint package.


%package python3
Summary: python3 components for the Pint package.
Group: Default
Requires: python3-core

%description python3
python3 components for the Pint package.


%prep
%setup -q -n Pint-0.8.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1532213268
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python3.7/site-packages python3 setup.py test || :
%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/Pint
cp LICENSE %{buildroot}/usr/share/doc/Pint/LICENSE
cp docs/_themes/LICENSE %{buildroot}/usr/share/doc/Pint/docs__themes_LICENSE
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(-,root,root,-)
/usr/share/doc/Pint/LICENSE
/usr/share/doc/Pint/docs__themes_LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
