#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : Pint
Version  : 0.8
Release  : 20
URL      : http://pypi.debian.net/Pint/Pint-0.8.tar.gz
Source0  : http://pypi.debian.net/Pint/Pint-0.8.tar.gz
Summary  : Physical quantities module
Group    : Development/Tools
License  : BSD-3-Clause
Requires: Pint-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
Pint: makes units easy
======================
Pint is a Python package to define, operate and manipulate physical
quantities: the product of a numerical value and a unit of measurement.
It allows arithmetic operations between them and conversions from and
to different units.

%package python
Summary: python components for the Pint package.
Group: Default
Provides: pint-python

%description python
python components for the Pint package.


%prep
%setup -q -n Pint-0.8

%build
export LANG=C
export SOURCE_DATE_EPOCH=1492438717
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python3.6/site-packages python3 setup.py test || :
%install
export SOURCE_DATE_EPOCH=1492438717
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python2*/*
/usr/lib/python3*/*
